services:
  app:
    container_name: app
    build: .
    ports:
      - 7860:7860
    volumes:
      - .:/code
    environment:
      - OLLAMA_API_BASE_URL=https://api.snowsecure.net
    networks:
      - local_network

  chromadb:
    container_name: chromadb
    image: chromadb/chroma:latest
    ports:
      - 8000:8000
    volumes:
      - ./data/chroma:/chroma/chroma
    networks:
      - local_network

networks:
  local_network:
    driver: bridge
